# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-07 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20171007_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(verbose_name='Setting Key')),
                ('value', models.TextField(verbose_name='Setting Value')),
            ],
        ),
    ]
