# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.DecimalField(decimal_places=25, max_digits=35, primary_key=True, serialize=False, verbose_name='Facebook ID')),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('info', models.TextField(verbose_name='info')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False, verbose_name='Setting Key')),
                ('value', models.TextField(verbose_name='Setting Value')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookInformation',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.Information')),
                ('facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Facebook')),
            ],
            bases=('assistant.information',),
        ),
        migrations.CreateModel(
            name='GreetingAnswer',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.Information')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Greeting')),
            ],
            bases=('assistant.information',),
        ),
        migrations.CreateModel(
            name='GreetingQuestion',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.Information')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Greeting')),
            ],
            bases=('assistant.information',),
        ),
    ]
