# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-08 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('info', models.TextField(verbose_name='info')),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='greeting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Setting Key'),
        ),
        migrations.CreateModel(
            name='GreetingAnswer',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.Information')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Greeting')),
            ],
            bases=('assistant.information',),
        ),
        migrations.CreateModel(
            name='GreetingQuestion',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistant.Information')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Greeting')),
            ],
            bases=('assistant.information',),
        ),
    ]
